os: osx
language: objective-c
before_install:
  - brew tap sevki/gcc_cross_compilers
  - brew tap homebrew/dupes
env:
  - ARCH=x64  GCC=$ARCH-elf-gcc BIN=$ARCH-elf-binutils GDB=$ARCH-elf-gdb
  - ARCH=arm  GCC=$ARCH-elf-gcc BIN=$ARCH-elf-binutils GDB=$ARCH-elf-gdb
  - ARCH=i386 GCC=$ARCH-elf-gcc BIN=$ARCH-elf-binutils GDB=$ARCH-elf-gdb
script:
  - brew audit $BIN
  - brew audit $GCC
  - brew audit $GDB
  - brew install -v $BIN
  - brew install -v $GCC
  - brew install -v $GDB
  - brew test $BIN
  - brew test $GCC
  - brew test $GDB
branches:
  only:
    - master
notifications:
  recipients:
    - s@sevki.org
  email:
    on_success: always
    on_failure: always
