os: osx
language: objective-c
before_install:
  - brew tap sevki/gcc_cross_compilers
  - brew tap homebrew/dupes
env:
  - ARCH=x64
  - ARCH=arm
  - ARCH=i386
script:
  - brew audit `$ARCH`-elf-binutils
  - brew audit `$ARCH`-elf-gcc
  - brew audit `$ARCH`-elf-gdb
  - brew install -v `$ARCH`-elf-binutils
  - brew install -v `$ARCH`-elf-gcc
  - brew install -v `$ARCH`-elf-gdb
  - brew test `$ARCH`-elf-binutils
  - brew test `$ARCH`-elf-gcc
  - brew test `$ARCH`-elf-gdb
branches:
  only:
    - master
notifications:
  recipients:
    - s@sevki.org
  email:
    on_success: always
    on_failure: always
