os: osx
language: objective-c
before_install:
  - brew update
  - brew upgrade
  - brew tap sevki/gcc_cross_compilers
script: 
  - brew install x64-elf-gcc
  - brew install i386-elf-gcc
  - brew install arm-elf-gcc
branches:
  only:
    - master
notifications:
  recipients:
    - s@sevki.org
  email:
    on_success: change
    on_failure: always
