os: osx
language: objective-c
before_install:
  - brew tap sevki/gcc_cross_compilers
  - brew tap homebrew/dupes
env:
  - ARCH=x64  elf-gcc BU=elf-binutils DBG=elf-dgb GCC=$ARCH-$COM BIN=$ARCH-$BU GDB=$ARCH-$DBG
  - ARCH=arm  elf-gcc BU=elf-binutils DBG=elf-dgb GCC=$ARCH-$COM BIN=$ARCH-$BU GDB=$ARCH-$DBG
  - ARCH=i386 elf-gcc BU=elf-binutils DBG=elf-dgb GCC=$ARCH-$COM BIN=$ARCH-$BU GDB=$ARCH-$DBG
script:
  - brew audit $BIN
  - brew audit $GCC
  - brew audit $GDB
  - brew install -v $BIN
  - brew install -v $GCC
  - brew install -v $GDB
  - brew test $BIN
  - brew test $GCC
  - brew test $GDB
branches:
  only:
    - master
notifications:
  recipients:
    - s@sevki.org
  email:
    on_success: always
    on_failure: always
